"""empty message

Revision ID: 3abc8e6406d3
Revises: 
Create Date: 2020-05-21 10:10:38.581997

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3abc8e6406d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
